HouseData <- read.table("~/exdata-data-household_power_consumption/household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
YearsHouseData <- HouseData[HouseData$Date %in% c("1/2/2007","2/2/2007") ,]
datedata <- strptime(paste(YearsHouseData$Date, YearsHouseData$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
PowerData <- as.numeric(YearsHouseData$Global_active_power)
ReactiveData <- as.numeric(YearsHouseData$Global_reactive_power)
VoltageData <- as.numeric(YearsHouseData$Voltage)
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2))
plot(datedata, PowerData, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(datedata, VoltageData, type="l", xlab="datetime", ylab="Voltage")
plot(datedata, as.numeric(YearsHouseData$Sub_metering_1), type="l", ylab="Energy Submetering", xlab="")
lines(datedata, as.numeric(YearsHouseData$Sub_metering_2), type="l", col="red")
lines(datedata, as.numeric(YearsHouseData$Sub_metering_3), type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
plot(datedata, ReactiveData, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()